language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install .
  - pip install -r requirements.txt -r test-requirements.txt
before_script:
  - flake8 --ignore=E501,W601,D203,D105 tsmppt60_driver
script:
  - coverage run --source=tsmppt60_driver setup.py test
after_success:
  - coveralls
