[project]
name = "tsmppt60-driver"
version = "0.2.3"
description = "Python module to get status of your solar charge controller TS-MPPT-60."
authors = [
    { name = "Takashi Ando", email = "dodo5522@gmail.com" },
]
urls = { homepage = "https://github.com/dodo5522/tsmppt60_driver" }
license = "GPLv2"
readme = "README.md"
requires-python = ">=3.11,<3.15"
packages = [{include = "tsmppt60_driver"}]
dependencies = []

[dependency-groups]
dev = [
    "pre-commit~=3.8",
    "pytest~=9.1",
    "pytest-mock~=3.12",
    "ruff~=0.16.3",
]

[tool.poetry]
requires-poetry = "~=2.4.1"

[tool.ruff]
target-version = "py311"
line-length = 120
extend-exclude = [
  "firebase",
  "infra",
]
select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "I",  # isort
  "C",  # flake8-comprehensions
  "B",  # flake8-bugbear
]
ignore = [
  "D203",
  "D105",
  "E501",  # line too long, handled by black
  "B008",  # do not perform function calls in argument defaults
  "C901",  # too complex
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.isort]
case-sensitive = true
lines-after-imports = 2

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
